# Empezando a programar

Esta es la primera clase

In [3]:
from pylab import *
%matplotlib inline

# Integer, Float y Double

In [7]:
1/2

0

In [20]:
a,d,e = 1.,5.,7; f=8.
b = 2
c = a/b

print f

8.0


In [12]:
a + b

3.0

In [13]:
a*b

2.0

In [14]:
b**2

4

In [15]:
2**2

4

In [16]:
b**a

2.0

In [21]:
4**(0.5)

2.0

# vectores

In [27]:
vector1 = [1.,2.,3.,4.]
c = vector1[2]/2

print c
print "La primera entrada es", vector1[0], "la segunda entrada es", vector1[1]

1.5
La primera entrada es 1.0 la segunda entrada es 2.0


In [28]:
print vector1

[1.0, 2.0, 3.0, 4.0]


In [30]:
array([1.,2.,3.,4.])

array([ 1.,  2.,  3.,  4.])

In [31]:
a = ["hola", [1,2,3], 507, 0.3]

In [32]:
a[0]

'hola'

In [33]:
zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [34]:
zeros((2,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [51]:
vector2 = ones(8)

In [53]:
vector2[0:5-1] = [11,12,13,14]
print vector2

[ 11.  12.  13.  14.   1.   1.   1.   1.]


In [55]:
vector3 = [1,2,3,4,5,6]
vector3[2:4] = [11,12]
print vector3

[1, 2, 11, 12, 5, 6]


In [68]:
matriz1 = [[1,2,3],[4,5,6],[7,8,9]]
print matriz1[1][2]
print matriz1[1,2]

101


TypeError: list indices must be integers, not tuple

In [64]:
matriz2 = zeros((3,3))
matriz2[1,1] = 5.
print matriz2[1,1]
print matriz2

5.0
[[ 0.  0.  0.]
 [ 0.  5.  0.]
 [ 0.  0.  0.]]


In [69]:
array([1,2,3,4])

array([1, 2, 3, 4])